# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run : |
          sudo apt-get update
          sudo apt-get install -y pandoc zip

      - name: generate html pages
        run: |
          wget https://github.com/hakimel/reveal.js/archive/master.zip
          unzip master.zip -d revealjs
          mkdir -p revealjs/reveal.js-master/dist/css
          mkdir -p revealjs/reveal.js-master/dist/js
          mv -p revealjs/reveal.js-master/dist/*.js* revealjs/reveal.js-master/dist/js
          mv -p revealjs/reveal.js-master/dist/*.css revealjs/reveal.js-master/dist/css
          cp -R revealjs/reveal.js-master/dist/theme revealjs/reveal.js-master/dist/css
          pandoc -s -V revealjs-url=./revealjs/reveal.js-master/dist -t revealjs -f markdown -o slides.html BookSummary/practices_of_agile_developer.md

      - name: publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


