# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run : |
          sudo apt-get update
          sudo apt-get install -y pandoc zip

      - name: generate html pages
        run: |
          wget https://github.com/hakimel/reveal.js/archive/master.zip
          unzip master.zip -d public/revealjs
          mkdir -p public/revealjs/reveal.js-master/dist/css
          mkdir -p public/revealjs/reveal.js-master/dist/js
          mv public/revealjs/reveal.js-master/dist/*.js* public/revealjs/reveal.js-master/dist/js
          mv public/revealjs/reveal.js-master/dist/*.css public/revealjs/reveal.js-master/dist/css
          cp -R public/revealjs/reveal.js-master/dist/theme public/revealjs/reveal.js-master/dist/css
          pandoc -s -f markdown -o public/index.html "BookSummary/book summary.md" -c sakura-dark-solarized.css
          pandoc -s -f markdown -o public/pytest.html "BookSummary/pytest_notes.md" -c sakura-dark-solarized.css
          pandoc -s -f markdown -o public/hands_on_ml.html "BookSummary/hands_on_ml.md" -c sakura-dark-solarized.css
          pandoc -s -V revealjs-url=revealjs/reveal.js-master/dist -t revealjs -f markdown -o public/practices_of_agile_developer.html BookSummary/practices_of_agile_developer.md --slide-level 2
          pandoc -s -V revealjs-url=revealjs/reveal.js-master/dist -t revealjs -f markdown -o public/domain_storytelling.html BookSummary/domain_storytelling.md --slide-level 2

      - name: publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


